# Generated by Django 6.0.1 on 2026-03-16 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
        ('property', '0010_propertyforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='unit_type',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.PROTECT, to='property.unittype'),
        ),
    ]
