image: atlassian/default-image:4

pipelines:
  branches:
    staging:
      - step:
          name: Deploy to Staging
          deployment: staging
          script:
            - pipe: atlassian/ssh-run:0.4.1
              variables:
                SSH_USER: $SSH_USER
                SERVER: $SERVER
                COMMAND: >
                  cd /var/www/akors-backend &&
                  sudo chown -R ubuntu:ubuntu . &&
                  git pull https://uj_simpalm:$GIT_PASSWORD@bitbucket.org/Simpalm/akors-backend.git staging &&
                  sudo chown -R www-data:www-data . &&
                  sudo systemctl restart gunicorn-akors &&
                  sudo service apache2 restart &&
                  uv run manage.py migrate