# Generated by Django 6.0.1 on 2026-01-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_role_table_alter_title_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('qei_number', models.CharField(max_length=100, null=True)),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=100)),
                ('email_verified_at', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roles', models.ManyToManyField(to='accounts.role')),
                ('titles', models.ManyToManyField(to='accounts.title')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
