# Generated by Django 6.0.1 on 2026-01-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_subscriptions_user_is_admin_user_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.subscriptions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='titles',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.title'),
        ),
    ]
