# Generated by Django 6.0.1 on 2026-02-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
