# Generated by Django 6.0.1 on 2026-03-09 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_customer_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='customer_number',
            new_name='customer_id',
        ),
    ]
