# Generated by Django 6.0.1 on 2026-03-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_stripe_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='units',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
