# Generated by Django 6.0.1 on 2026-03-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_subscriptions_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='units',
            field=models.IntegerField(max_length=8),
        ),
    ]
