# Generated by Django 6.0.1 on 2026-03-09 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_subscriptions_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='units',
            field=models.IntegerField(),
        ),
    ]
