# Generated by Django 6.0.1 on 2026-03-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_refreshtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='token',
            field=models.CharField(max_length=200),
        ),
    ]
