# Generated by Django 6.0.1 on 2026-03-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_refreshtoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtoken',
            name='uuid',
            field=models.CharField(default='UUID', max_length=100),
        ),
    ]
