# Generated by Django 6.0.1 on 2026-02-24 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_rename_certificate_url_unit_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertymanagement',
            old_name='user',
            new_name='manager',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='property',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='user',
        ),
        migrations.AddField(
            model_name='forms',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='property.state'),
        ),
        migrations.AlterField(
            model_name='propertymanagement',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='property.state'),
        ),
    ]
