# Generated by Django 6.0.1 on 2026-03-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_rename_user_propertymanagement_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
