# Generated by Django 6.0.1 on 2026-03-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_state_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
