# Generated by Django 6.0.1 on 2026-03-12 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_alter_state_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forms',
        ),
    ]
