# Generated by Django 6.0.1 on 2026-03-12 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_delete_forms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertymanagement',
            old_name='building_name',
            new_name='name',
        ),
    ]
