# Generated by Django 6.0.1 on 2026-03-13 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
        ('property', '0009_propertymanagement_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='forms.forms')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='property.propertymanagement')),
            ],
            options={
                'db_table': 'property_forms',
            },
        ),
    ]
