# Generated by Django 6.0.1 on 2026-03-16 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_propertyforms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='name',
            new_name='nickname',
        ),
    ]
