# Generated by Django 6.0.1 on 2026-03-16 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_rename_name_unit_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='url',
            new_name='certificate',
        ),
    ]
