# Generated by Django 6.0.1 on 2026-04-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_alter_images_url_alter_unit_certificate_unitform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymanagement',
            name='state_registration',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
