# Generated by Django 6.0.1 on 2026-05-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_alter_propertymanagement_state_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='state_registration',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
