# Generated by Django 6.0.1 on 2026-05-05 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_alter_unit_state_registration_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.propertyforms'),
        ),
    ]
