# Generated by Django 6.0.1 on 2026-05-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_alter_images_form_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
    ]
