# Generated by Django 6.0.1 on 2026-06-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_unit_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='form',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
