# Generated by Django 6.0.1 on 2026-06-09 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_alter_images_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.propertyforms'),
        ),
    ]
